apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: httpd
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: bitnami/apache
    referencePolicy:
      type: Source
      tag: v1

